### ISSUE TITLE
Fix names for SNARE

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#184]
Chris emailed with Blue Lake and came to this conclusion:

> FYI,
> Blue has clarified how Snare RNAseq & ATACseq should be classified. In short:
> 
>> They both are single nucleus assays, but for ATAC the assay is referred to as scATAC-seq (10X scATAC-seq also involves nuclei)
>
> SNARE-seq2 has 2 components :
>    SNARE-RNAseq should be under snRNA-seq
> &
>    SNARE-ATACseq should be under scATAC-seq

**Comment by mccalluc** [comment]
These are the terms in assay-types.yaml which include `SNARE`:
```
SNAREseq:
    description: SNARE-seq
salmon_rnaseq_snareseq:
    description: scRNA-seq (SNARE-seq) [Salmon]
sc_atac_seq_snare:
    description: scATAC-seq (SNARE-seq) [SnapATAC]
sc_rna_seq_snare_lab:
    description: scRNA-seq (SNARE-seq) [Lab Processed]
sc_atac_seq_snare_lab:
    description: scATAC-seq (SNARE-seq) [Lab Processed]
```
@cebriggs7135 : Can you make a PR, from the devel branch, with the changes? Or can you state precisely what these lines should be changed to, and I'll make the PR?
