### ISSUE TITLE
assay_types.yaml should be deleted, information should come from commons instead.

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#268]
`assay_types.yaml` looks like:
```
AF:
    description: Autofluorescence Microscopy
    alt-names: []
    primary: true
    vitessce-hints: []
...
```
It is used to get the display names for the assays at index time.

@jswelling : Can you confirm that this should be coming from commons, instead of being encoded here? And it's probably in my court to fix this, right?
