### ISSUE TITLE
Misspelled properties

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#8]
(If the real fix is in the Neo4j, feel free to move this issue to another repo.)

Run this:
```
ES='https://search-hubmap-entity-es-dev-zhdpuhhf2vjpvqfq7zmn2gdgqq.us-east-1.es.amazonaws.com/'
curl ${ES}entities?format=yaml | grep -v '       '
```

Some of the properties are misspelled:
```
      ancenstor_ids: # "ancestor"
      ancenstors:
      descentdant_ids: # "descendant"
      descentdants:
      entitytype: # "entity_type", probably?
```
