### ISSUE TITLE
Log search queries per index group based on configuration

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/search-api#874]
Add a new boolean configuration `log_query` in `search-config.yaml` (and `search-config.yaml.example` too) so that we can turn on/off the query logging per index group. Harvard team requested this feature to analyze the search queries (json body) sent to the `portal` public and consortium indices.

```
indices:
  entities: 
    active: true
    log_query: false
    ...
    
  portal: 
    active: true
    log_query: true
    ...
```

- This new configuration will be used in [search-adaptor](https://github.com/dbmi-pitt/search-adaptor) to log the search queries to CloudWatch as `logging.INFO` level. 
- Only generate the log when `log_query` exists and set to `true`, so it doesn't require the SenNet team to support this feature
